#-*- coding: UTF-8 -*-
import os
import sys
import time
import datetime
from sys import path
path.append('%s/' % os.getenv('SCS_PATH'))

from BaseStat import BasePGStat, get_stat_date, BasePGCluster

"""留存组合数据处理"""
class agg_ret_delete_update(BasePGCluster):

    def stat(self):

        sql = """
create table dcnew.reg_user_actret_20171225_data (like dcnew.reg_user_actret);
    insert into dcnew.reg_user_actret_20171225_data ( fdate,
fgamefsk,
fplatformfsk,
fhallfsk,
fsubgamefsk,
fterminaltypefsk,
fversionfsk,
fchannelcode,
f1daycnt,
f2daycnt,
f3daycnt,
f4daycnt,
f5daycnt,
f6daycnt,
f7daycnt,
f14daycnt,
f30daycnt,
f60daycnt,
f90daycnt )  select fdate,
fgamefsk,
fplatformfsk,
-21379 fhallfsk,
fsubgamefsk,
fterminaltypefsk,
fversionfsk,
fchannelcode,
sum(f1daycnt),
sum(f2daycnt),
sum(f3daycnt),
sum(f4daycnt),
sum(f5daycnt),
sum(f6daycnt),
sum(f7daycnt),
sum(f14daycnt),
sum(f30daycnt),
sum(f60daycnt),
sum(f90daycnt) from dcnew.reg_user_actret where fdate >= '2017-09-27' and fdate <= '2017-12-23' and fversionfsk = -21379 and fhallfsk <> -21379 and fsubgamefsk = -21379 and fterminaltypefsk = -21379 group by fdate,
fgamefsk,
fplatformfsk,
fsubgamefsk,
fterminaltypefsk,
fversionfsk,fchannelcode;
    insert into dcnew.reg_user_actret ( fdate,
fgamefsk,
fplatformfsk,
fhallfsk,
fsubgamefsk,
fterminaltypefsk,
fversionfsk,
fchannelcode,
f1daycnt,
f2daycnt,
f3daycnt,
f4daycnt,
f5daycnt,
f6daycnt,
f7daycnt,
f14daycnt,
f30daycnt,
f60daycnt,
f90daycnt ) select  fdate,
fgamefsk,
fplatformfsk,
fhallfsk,
fsubgamefsk,
fterminaltypefsk,
fversionfsk,
fchannelcode,
f1daycnt,
f2daycnt,
f3daycnt,
f4daycnt,
f5daycnt,
f6daycnt,
f7daycnt,
f14daycnt,
f30daycnt,
f60daycnt,
f90daycnt  from dcnew.reg_user_actret_20171225_data;
drop table dcnew.reg_user_actret_20171225_data;



create table dcnew.act_user_actret_20171225_data (like dcnew.act_user_actret);
    insert into dcnew.act_user_actret_20171225_data ( fdate,
fgamefsk,
fplatformfsk,
fhallfsk,
fsubgamefsk,
fterminaltypefsk,
fversionfsk,
fchannelcode,
f1daycnt,
f2daycnt,
f3daycnt,
f4daycnt,
f5daycnt,
f6daycnt,
f7daycnt,
f14daycnt,
f30daycnt,
f60daycnt,
f90daycnt )  select fdate,
fgamefsk,
fplatformfsk,
-21379 fhallfsk,
fsubgamefsk,
fterminaltypefsk,
fversionfsk,
fchannelcode,
sum(f1daycnt),
sum(f2daycnt),
sum(f3daycnt),
sum(f4daycnt),
sum(f5daycnt),
sum(f6daycnt),
sum(f7daycnt),
sum(f14daycnt),
sum(f30daycnt),
sum(f60daycnt),
sum(f90daycnt) from dcnew.act_user_actret where fdate >= '2017-09-27' and fdate <= '2017-12-23' and fversionfsk = -21379 and fhallfsk <> -21379 and fsubgamefsk = -21379 and fterminaltypefsk = -21379 group by fdate,
fgamefsk,
fplatformfsk,
fsubgamefsk,
fterminaltypefsk,
fversionfsk,fchannelcode;
    insert into dcnew.act_user_actret ( fdate,
fgamefsk,
fplatformfsk,
fhallfsk,
fsubgamefsk,
fterminaltypefsk,
fversionfsk,
fchannelcode,
f1daycnt,
f2daycnt,
f3daycnt,
f4daycnt,
f5daycnt,
f6daycnt,
f7daycnt,
f14daycnt,
f30daycnt,
f60daycnt,
f90daycnt ) select  fdate,
fgamefsk,
fplatformfsk,
fhallfsk,
fsubgamefsk,
fterminaltypefsk,
fversionfsk,
fchannelcode,
f1daycnt,
f2daycnt,
f3daycnt,
f4daycnt,
f5daycnt,
f6daycnt,
f7daycnt,
f14daycnt,
f30daycnt,
f60daycnt,
f90daycnt  from dcnew.act_user_actret_20171225_data;
drop table dcnew.act_user_actret_20171225_data;




create table dcnew.play_user_actret_20171225_data (like dcnew.play_user_actret);
    insert into dcnew.play_user_actret_20171225_data ( fdate,
fgamefsk,
fplatformfsk,
fhallfsk,
fsubgamefsk,
fterminaltypefsk,
fversionfsk,
fchannelcode,
f1daycnt,
f2daycnt,
f3daycnt,
f4daycnt,
f5daycnt,
f6daycnt,
f7daycnt,
f14daycnt,
f30daycnt,
f60daycnt,
f90daycnt )  select fdate,
fgamefsk,
fplatformfsk,
-21379 fhallfsk,
fsubgamefsk,
fterminaltypefsk,
fversionfsk,
fchannelcode,
sum(f1daycnt),
sum(f2daycnt),
sum(f3daycnt),
sum(f4daycnt),
sum(f5daycnt),
sum(f6daycnt),
sum(f7daycnt),
sum(f14daycnt),
sum(f30daycnt),
sum(f60daycnt),
sum(f90daycnt) from dcnew.play_user_actret where fdate >= '2017-09-27' and fdate <= '2017-12-22' and fversionfsk = -21379 and fhallfsk <> -21379 and fsubgamefsk = -21379 and fterminaltypefsk = -21379 group by fdate,
fgamefsk,
fplatformfsk,
fsubgamefsk,
fterminaltypefsk,
fversionfsk,fchannelcode;
    insert into dcnew.play_user_actret ( fdate,
fgamefsk,
fplatformfsk,
fhallfsk,
fsubgamefsk,
fterminaltypefsk,
fversionfsk,
fchannelcode,
f1daycnt,
f2daycnt,
f3daycnt,
f4daycnt,
f5daycnt,
f6daycnt,
f7daycnt,
f14daycnt,
f30daycnt,
f60daycnt,
f90daycnt ) select  fdate,
fgamefsk,
fplatformfsk,
fhallfsk,
fsubgamefsk,
fterminaltypefsk,
fversionfsk,
fchannelcode,
f1daycnt,
f2daycnt,
f3daycnt,
f4daycnt,
f5daycnt,
f6daycnt,
f7daycnt,
f14daycnt,
f30daycnt,
f60daycnt,
f90daycnt  from dcnew.play_user_actret_20171225_data;
drop table dcnew.play_user_actret_20171225_data;


        COMMIT;
        """ % self.sql_dict
        self.exe_hql(sql)


if __name__ == "__main__":

    stat_date = get_stat_date()
    # 生成统计实例
    a = agg_ret_delete_update(stat_date)
    a()
