#!/usr/local/python272/bin/python
# -*- coding: UTF-8 -*-

import os
import sys
import datetime
from sys import path
path.append('%s/' % os.getenv('SCS_PATH'))
from BaseStatModel import BaseStatModel
import service.sql_const as sql_const


class UserPortraitInfo(BaseStatModel):
    def create_tab(self):
        hql = """
            CREATE TABLE IF NOT EXISTS veda.dfqp_user_portrait(
              mid bigint COMMENT 'MID',
              nickname string COMMENT '昵称',
              signup_time string COMMENT '注册时间',
              latest_login_time string  COMMENT '最后登录时间',
              lifespan int COMMENT '生命周期(最后登录-注册时间)',
              signup_to_now_days int COMMENT '注册至今天数',
              signup_channel_code int COMMENT '注册渠道代码',
              signup_device_type string COMMENT '注册设备型号',
              signup_device_pixel string COMMENT '注册设备分辨率',
              signup_device_imei string COMMENT '注册设备码',
              signup_os string COMMENT '注册设备操作系统',
              signup_ip string COMMENT '注册IP',
              signup_ip_country string COMMENT '注册IP所属国家',
              signup_ip_province string COMMENT '注册IP所属省份',
              signup_ip_city string COMMENT '注册IP所属城市',
              realname string COMMENT '真实姓名',
              realname_certify_date string COMMENT '实名认证日期',
              gender string COMMENT '性别',
              birthday string COMMENT '生日',
              star_sign string COMMENT '星座',
              age int COMMENT '年龄',
              phone_number string COMMENT '手机号',
              email string COMMENT '电子邮箱',
              id_card_number string COMMENT '身份证号码',
              cid string COMMENT 'CID',
              total_silver_coin bigint COMMENT '总银币',
              carrying_silver_coin bigint COMMENT '携带银币',
              safebox_silver_coin bigint COMMENT '保险箱银币',
              total_gold_bar bigint COMMENT '总金条',
              carrying_gold_bar bigint COMMENT '携带金条',
              safebox_gold_bar bigint COMMENT '保险箱金条',
              carrying_items_value int COMMENT '携带道具价值',
              max_silver_coin bigint COMMENT '历史最大银币量',
              max_silver_date string COMMENT '历史最大银币日期',
              max_gold_bar bigint COMMENT '历史最大金条量',
              max_gold_date string COMMENT '历史最大金条日期',
              vip_level int COMMENT 'VIP等级',
              vip_type int COMMENT 'VIP类型',
              vip_expire_time string COMMENT 'VIP到期时间',
              user_status string COMMENT '用户状态',
              user_type bigint COMMENT '用户类型(登录入口)',
              app_version string COMMENT '当前应用版本',
              latest_located_latitude string COMMENT '最后所在位置纬度',
              latest_located_longitude string COMMENT '最后所在位置经度',
              device_simulator_flag string COMMENT '模拟器标识',
              signup_exception_flag int COMMENT '异常新增标识',
              fluctuometer_flag int COMMENT '波动计标识',
              active_exception_flag int COMMENT '异常活跃标识',
              multiple_account_flag int COMMENT '多账号标识',
              user_identity int COMMENT '用户身份',
              superior_agent string COMMENT '上级代理商',
              superior_promoter string COMMENT '上级推广员',
              login_days int COMMENT '登录天数',
              play_days int COMMENT '玩牌天数',
              bankrupt_days int COMMENT '破产天数',
              relieve_days int COMMENT '领取救济天数',
              match_days int COMMENT '比赛天数',
              login_count int COMMENT '登录次数',
              total_innings int COMMENT '玩牌局数',
              win_innings int COMMENT '胜局数',
              lose_innings int COMMENT '输局数',
              play_duration int COMMENT '玩牌时长(秒)',
              pay_count int COMMENT '付费次数',
              pay_sum decimal(10,2) COMMENT '付费总额',
              match_enroll_count int COMMENT '比赛报名次数',
              match_innings int COMMENT '比赛局数',
              match_duration int COMMENT '比赛时长(秒)',
              match_win_innings int COMMENT '比赛获胜局数',
              bankrupt_count int COMMENT '破产次数',
              relieve_count int COMMENT '领取救济次数',
              relieve_silver_coins bigint COMMENT '领取救济总额',
              latest_active_time string COMMENT '最后活跃时间',
              latest_play_time string COMMENT '最后玩牌时间',
              latest_pay_time string COMMENT '最后付费时间',
              latest_pay_money decimal(10,2) COMMENT '最后付费金额',
              latest_match_time string COMMENT '最后比赛时间',
              latest_bankrupt_time string COMMENT '最后破产时间',
              latest_relieve_time string COMMENT '最后领取救济时间',
              first_login_time string COMMENT '首次登录时间',
              first_play_time string COMMENT '首次玩牌时间',
              first_pay_time string COMMENT '首次付费时间',
              first_match_time string COMMENT '首次比赛时间',
              first_bankrupt_time string COMMENT '首次破产时间',
              first_relieve_time string COMMENT '首次领取救济时间',
              last_2nd_login_time string COMMENT '最后登录上一次时间',
              last_2nd_active_time string COMMENT '最后活跃上一次时间',
              last_2nd_play_time string COMMENT '最后玩牌上一次时间',
              last_2nd_pay_time string COMMENT '最后付费上一次时间',
              last_2nd_match_time string COMMENT '最后比赛上一次时间',
              latest_device_imei string COMMENT '最后登录设备IMEI',
              latest_device_imsi string COMMENT '最后登录设备IMSI',
              latest_device_type string COMMENT '最后登录设备型号',
              latest_device_pixel string COMMENT '最后登录设备分辨率',
              latest_device_os string COMMENT '最后登录操作系统',
              latest_app_version string COMMENT '最后登录版本',
              latest_network string COMMENT '最后登录网络类型',
              latest_operator string COMMENT '最后登录运营商',
              latest_login_ip string COMMENT '最后登录IP',
              latest_login_ip_country string COMMENT '最后登录IP所属国家',
              latest_login_ip_province string COMMENT '最后登录IP所属省份',
              latest_login_ip_city string COMMENT '最后登录IP所属城市',
              recent_login_series_days int COMMENT '最近连续登录天数',
              max_login_series_days int COMMENT '最大连续登录天数',
              latest_pname string COMMENT '最后玩牌一次场次',
              latest_subname string COMMENT '最后玩牌二级场次',
              latest_gsubname string COMMENT '最后玩牌三级场次',
              latest_play_coins bigint COMMENT '最后玩牌输赢货币量',
              purchase_silver_money decimal(10,2) COMMENT '付费购买银币金额',
              purchase_gold_money decimal(10,2) COMMENT '付费购买金条金额',
              purchase_vip_money decimal(10,2) COMMENT '付费购买VIP金额',
              purchase_items_money decimal(10,2) COMMENT '付费购买其它物品金额',
              max_pay_money decimal(10,2) COMMENT '最大付费金额',
              match_entry_fee bigint COMMENT '比赛总报名费',
              max_match_entry_fee bigint COMMENT '比赛最大报名费',
              latest_match_pname string COMMENT '最后比赛一次场次',
              latest_match_subname string COMMENT '最后比赛二级场次',
              latest_match_gsubname string COMMENT '最后比赛三级场次',
              match_reward decimal(10,2) COMMENT '比赛获奖总金额',
              max_match_reward decimal(10,2) COMMENT '比赛最大获奖金额',
              silver_innings int COMMENT '银币场玩牌局数',
              silver_duration int COMMENT '银币场玩牌时长(秒)',
              silver_win_innings int COMMENT '银币场胜局数',
              silver_lose_innings int COMMENT '银币场输局数',
              silver_service_charge bigint COMMENT '银币场台费',
              silver_net_coins bigint COMMENT '银币场净输赢银币',
              silver_win_coins bigint COMMENT '银币场赢取银币',
              silver_lose_coins bigint COMMENT '银币场输去银币',
              silver_max_win_coins bigint COMMENT '银币场最大赢取银币',
              silver_max_lose_coins bigint COMMENT '银币场最大输去银币',
              gold_innings int COMMENT '金条场玩牌局数',
              gold_duration int COMMENT '金条场玩牌时长(秒)',
              gold_win_innings int COMMENT '金条场胜局数',
              gold_lose_innings int COMMENT '金条场输局数',
              gold_service_charge bigint COMMENT '金条场台费',
              gold_net_coins bigint COMMENT '金条场净输赢金条',
              gold_win_coins bigint COMMENT '金条场赢取金条',
              gold_lose_coins bigint COMMENT '金条场输去金条',
              gold_max_win_coins bigint COMMENT '金条场最大赢取金条',
              gold_max_lose_coins bigint COMMENT '金条场最大输去金条',
              score_innings int COMMENT '积分场玩牌局数',
              score_duration int COMMENT '积分场玩牌时长(秒)',
              score_win_innings int COMMENT '积分场胜局数',
              score_lose_innings int COMMENT '积分场输局数',
              score_service_charge bigint COMMENT '积分场台费',
              score_net_points bigint COMMENT '积分场净输赢积分',
              score_win_points bigint COMMENT '积分场赢取积分',
              score_lose_points bigint COMMENT '积分场输去积分',
              score_max_win_points bigint COMMENT '积分场最大赢取积分',
              score_max_lose_points bigint COMMENT '积分场最大输去积分',
              if_signup_2days char(1) COMMENT '是否已注册2天',
              if_signup_3days char(1) COMMENT '是否已注册3天',
              if_signup_7days char(1) COMMENT '是否已注册7天',
              if_signup_15days char(1) COMMENT '是否已注册15天',
              if_signup_30days char(1) COMMENT '是否已注册30天',
              if_signup_60days char(1) COMMENT '是否已注册60天',
              if_signup_90days char(1) COMMENT '是否已注册90天',
              if_away_7days char(1) COMMENT '是否已流失7天',
              if_away_15days char(1) COMMENT '是否已流失15天',
              if_away_30days char(1) COMMENT '是否已流失30天',
              if_away_60days char(1) COMMENT '是否已流失60天',
              if_away_90days char(1) COMMENT '是否已流失90天',
              fbpid string COMMENT 'BPID',
              fgamefsk bigint COMMENT '游戏ID',
              fgamename string COMMENT '游戏名称',
              fplatformfsk bigint COMMENT '平台ID',
              fplatformname string COMMENT '平台名称',
              fhallfsk bigint COMMENT '大厅ID',
              fhallname string COMMENT '大厅名称',
              fterminaltypefsk bigint COMMENT '终端ID',
              fterminaltypename string COMMENT '终端名称',
              fversionfsk bigint COMMENT '版本ID',
              fversionname string COMMENT '版本名称')
            COMMENT '地方棋牌用户信息(画像表)'
            STORED AS PARQUET
        """
        res = self.sql_exe(hql)
        if res != 0:
            return res
        return res

    def stat(self):
        hql = """
            insert overwrite table veda.dfqp_user_portrait
            select t1.mid,
                   nickname,
                   signup_time,
                   t1.latest_login_time,
                   lifespan,
                   signup_to_now_days,
                   signup_channel_code,
                   signup_device_type,
                   signup_device_pixel,
                   signup_device_imei,
                   signup_os,
                   signup_ip,
                   signup_ip_country,
                   signup_ip_province,
                   signup_ip_city,
                   realname,
                   realname_certify_date,
                   gender,
                   birthday,
                   star_sign,
                   age,
                   phone_number,
                   email,
                   id_card_number,
                   cid,
                   total_silver_coin,
                   carrying_silver_coin,
                   safebox_silver_coin,
                   total_gold_bar,
                   carrying_gold_bar,
                   safebox_gold_bar,
                   carrying_items_value,
                   max_silver_coin,
                   max_silver_date,
                   max_gold_bar,
                   max_gold_date,
                   vip_level,
                   vip_type,
                   vip_expire_time,
                   user_status,
                   user_type,
                   app_version,
                   latest_located_latitude,
                   latest_located_longitude,
                   device_simulator_flag,
                   signup_exception_flag,
                   fluctuometer_flag,
                   active_exception_flag,
                   multiple_account_flag,
                   user_identity,
                   superior_agent,
                   superior_promoter,
                   login_days,
                   play_days,
                   bankrupt_days,
                   relieve_days,
                   match_days,
                   login_count,
                   total_innings,
                   win_innings,
                   lose_innings,
                   play_duration,
                   pay_count,
                   pay_sum,
                   match_enroll_count,
                   match_innings,
                   match_duration,
                   match_win_innings,
                   bankrupt_count,
                   relieve_count,
                   relieve_silver_coins,
                   latest_active_time,
                   latest_play_time,
                   latest_pay_time,
                   latest_pay_money,
                   latest_match_time,
                   latest_bankrupt_time,
                   latest_relieve_time,
                   first_login_time,
                   first_play_time,
                   first_pay_time,
                   first_match_time,
                   first_bankrupt_time,
                   first_relieve_time,
                   last_2nd_login_time,
                   last_2nd_active_time,
                   last_2nd_play_time,
                   last_2nd_pay_time,
                   last_2nd_match_time,
                   latest_device_imei,
                   latest_device_imsi,
                   latest_device_type,
                   latest_device_pixel,
                   latest_device_os,
                   latest_app_version,
                   latest_network,
                   latest_operator,
                   latest_login_ip,
                   latest_login_ip_country,
                   latest_login_ip_province,
                   latest_login_ip_city,
                   recent_login_series_days,
                   max_login_series_days,
                   latest_pname,
                   latest_subname,
                   latest_gsubname,
                   latest_play_coins,
                   purchase_silver_money,
                   purchase_gold_money,
                   purchase_vip_money,
                   purchase_items_money,
                   max_pay_money,
                   match_entry_fee,
                   max_match_entry_fee,
                   latest_match_pname,
                   latest_match_subname,
                   latest_match_gsubname,
                   match_reward,
                   max_match_reward,
                   silver_innings,
                   silver_duration,
                   silver_win_innings,
                   silver_lose_innings,
                   silver_service_charge,
                   silver_net_coins,
                   silver_win_coins,
                   silver_lose_coins,
                   silver_max_win_coins,
                   silver_max_lose_coins,
                   gold_innings,
                   gold_duration,
                   gold_win_innings,
                   gold_lose_innings,
                   gold_service_charge,
                   gold_net_coins,
                   gold_win_coins,
                   gold_lose_coins,
                   gold_max_win_coins,
                   gold_max_lose_coins,
                   score_innings,
                   score_duration,
                   score_win_innings,
                   score_lose_innings,
                   score_service_charge,
                   score_net_points,
                   score_win_points,
                   score_lose_points,
                   score_max_win_points,
                   score_max_lose_points,
                   if_signup_2days,
                   if_signup_3days,
                   if_signup_7days,
                   if_signup_15days,
                   if_signup_30days,
                   if_signup_60days,
                   if_signup_90days,
                   if_away_7days,
                   if_away_15days,
                   if_away_30days,
                   if_away_60days,
                   if_away_90days,
                   fbpid,
                   fgamefsk,
                   fgamename,
                   fplatformfsk,
                   fplatformname,
                   fhallfsk,
                   fhallname,
                   fterminaltypefsk,
                   fterminaltypename,
                   fversionfsk,
                   fversionname
              from dim.bpid_map t0
             inner join veda.dfqp_user_portrait_basic t1
                on t0.fbpid = t1.signup_bpid
             inner join veda.dfqp_user_portrait_career t2
                on t1.mid = t2.mid
             order by t1.mid
        """
        res = self.sql_exe(hql)
        if res != 0:
            return res

        return res


# 实例化执行
a = UserPortraitInfo(sys.argv[1:])
a()