#!/usr/local/python272/bin/python
# -*- coding: UTF-8 -*-

import os
import sys
import datetime
from sys import path
path.append('%s/' % os.getenv('SCS_PATH'))
from BaseStatModel import BaseStatModel
import service.sql_const as sql_const


class agg_user_crowd(BaseStatModel):
    def create_tab(self):
        hql = """
            CREATE TABLE IF NOT EXISTS veda.user_attributes
            (
              fgamefsk bigint COMMENT '游戏ID',
              fgamename string COMMENT '游戏名称',
              fplatformfsk bigint COMMENT '平台ID',
              fplatformname string COMMENT '平台名称',
              fhallfsk bigint COMMENT '大厅ID',
              fhallname string COMMENT '大厅名称',
              fterminaltypefsk bigint COMMENT '终端ID',
              fterminaltypename string COMMENT '终端名称',
              fversionfsk bigint COMMENT '版本ID',
              fversionname string COMMENT '版本名称',
              fuid bigint COMMENT '用户ID',
              signup_time string COMMENT '注册时间',
              signup_to_now_days int COMMENT '注册至今天数',
              lifespan int COMMENT '生命周期(注册~最后登录)',
              signup_channel_code int COMMENT '注册渠道代码',
              signup_device_type string COMMENT '注册设备型号',
              signup_device_pixel string COMMENT '注册设备分辨率',
              signup_device_imei string COMMENT '注册设备码',
              signup_ip string COMMENT '注册IP',
              signup_ip_country string COMMENT '注册IP所属国家',
              signup_ip_province string COMMENT '注册IP所属省份',
              signup_ip_city string COMMENT '注册IP所属城市',
              gender string COMMENT '性别',
              email string COMMENT '电子邮箱',
              total_silver_coin bigint COMMENT '游戏币资产(携带+保险箱)',
              carrying_silver_coin bigint COMMENT '携带游戏币',
              safebox_silver_coin bigint COMMENT '保险箱游戏币',
              total_gold_bar bigint COMMENT '金条资产(携带+保险箱)',
              carrying_gold_bar bigint COMMENT '携带金条',
              safebox_gold_bar bigint COMMENT '保险箱金条',
              carrying_items_value bigint COMMENT '携带道具价值',
              login_days int COMMENT '登录天数',
              login_count int COMMENT '登录次数',
              recent_login_series_days int COMMENT '当前连续登录天数',
              max_login_series_days int COMMENT '最大连续登录天数',
              last_2nd_login_time string COMMENT '最后登录上一次时间',
              latest_login_time string COMMENT '最后登录时间',
              latest_login_ip_country string COMMENT '最后登录IP所属国家',
              latest_login_ip_province string COMMENT '最后登录IP所属省份',
              latest_login_ip_city string COMMENT '最后登录IP所属城市',
              play_days int COMMENT '玩牌天数',
              play_duration int COMMENT '玩牌时长(分钟)',
              match_days int COMMENT '比赛天数',
              match_duration int COMMENT '比赛时长(分钟)',
              match_enroll_count int COMMENT '比赛报名次数',
              match_innings int COMMENT '比赛局数',
              pay_sum decimal(10,2) COMMENT '付费总额(地方棋牌:人民币，德州扑克:美元)',
              pay_count int COMMENT '付费次数',
              first_pay_time string COMMENT '首次付费时间',
              last_2nd_pay_time string COMMENT '最后付费上一次时间',
              latest_pay_time string COMMENT '最后付费时间',
              bankrupt_days int COMMENT '破产天数',
              bankrupt_count int COMMENT '破产次数',
              relieve_days int COMMENT '领取救济天数',
              relieve_count int COMMENT '领取救济次数',
              game_duration_avg30day int COMMENT '近30日平均游戏时长(分钟)',
              game_duration_avg15day int COMMENT '近15日平均游戏时长(分钟)',
              game_duration_avg7day int COMMENT '近7日平均游戏时长(分钟)',
              game_duration_avg3day int COMMENT '近3日平均游戏时长(分钟)',
              game_passion_trend string COMMENT '活跃走势',
              game_passion_alteration decimal(3,2) COMMENT '活跃度升降',
              payment_amount_avg60day decimal(10,2) COMMENT '近60日平均付费(元)',
              payment_amount_avg30day decimal(10,2) COMMENT '近30日平均付费(元)',
              payment_amount_avg15day decimal(10,2) COMMENT '近15日平均付费(元)',
              payment_amount_avg7day decimal(10,2) COMMENT '近7日平均付费(元)',
              pay_passion_trend string COMMENT '付费走势',
              pay_passion_alteration decimal(3,2) COMMENT '付费热情升降'
            )
            COMMENT '用户属性（bud用户分群数据）'
            STORED AS parquet
        """
        res = self.sql_exe(hql)
        if res != 0:
            return res

        return res

    def stat(self):
        hql = """
            insert overwrite table veda.user_attributes
            select t1.fgamefsk,
                   t1.fgamename,
                   t1.fplatformfsk,
                   t1.fplatformname,
                   t1.fhallfsk,
                   t1.fhallname,
                   t1.fterminaltypefsk,
                   t1.fterminaltypename,
                   t1.fversionfsk,
                   t1.fversionname,
                   t1.mid as fuid,
                   signup_time,
                   signup_to_now_days,
                   lifespan,
                   signup_channel_code,
                   signup_device_type,
                   signup_device_pixel,
                   signup_device_imei,
                   signup_ip,
                   signup_ip_country,
                   signup_ip_province,
                   signup_ip_city,
                   gender,
                   email,
                   total_silver_coin,
                   carrying_silver_coin,
                   safebox_silver_coin,
                   total_gold_bar,
                   carrying_gold_bar,
                   safebox_gold_bar,
                   carrying_items_value,
                   login_days,
                   login_count,
                   recent_login_series_days,
                   max_login_series_days,
                   last_2nd_login_time,
                   latest_login_time,
                   latest_login_ip_country,
                   latest_login_ip_province,
                   latest_login_ip_city,
                   play_days,
                   ceil(play_duration/60) as play_duration,
                   match_days,
                   ceil(match_duration/60) as match_duration,
                   match_enroll_count,
                   match_innings,
                   pay_sum,
                   pay_count,
                   first_pay_time,
                   last_2nd_pay_time,
                   latest_pay_time,
                   bankrupt_days,
                   bankrupt_count,
                   relieve_days,
                   relieve_count,
                   game_duration_avg30day,
                   game_duration_avg15day,
                   game_duration_avg7day,
                   game_duration_avg3day,
                   t2.trend as game_passion_trend,
                   t2.alteration as game_passion_alteration,
                   payment_amount_avg60day,
                   payment_amount_avg30day,
                   payment_amount_avg15day,
                   payment_amount_avg7day,
                   t3.trend as pay_passion_trend,
                   t3.alteration as pay_passion_alteration
              from veda.dfqp_user_portrait t1
              left join veda.user_activity_alteration t2
                on (t1.fgamefsk = t2.fgamefsk and t1.fplatformfsk = t2.fplatformfsk and t1.mid = t2.fuid)
              left join veda.user_payment_alteration t3
                on (t1.fgamefsk = t3.fgamefsk and t1.fplatformfsk = t3.fplatformfsk and t1.mid = t3.fuid)
            union all
            select t1.fgamefsk,
                   t1.fgamename,
                   t1.fplatformfsk,
                   t1.fplatformname,
                   t1.fhallfsk,
                   t1.fhallname,
                   t1.fterminaltypefsk,
                   t1.fterminaltypename,
                   t1.fversionfsk,
                   t1.fversionname,
                   t1.fuid,
                   signup_time,
                   signup_to_now_days,
                   lifespan,
                   signup_channel_code,
                   signup_device_type,
                   signup_device_pixel,
                   signup_device_imei,
                   cast(null as string) as signup_ip,
                   country as signup_ip_country,
                   cast(null as string) as signup_ip_province,
                   city as signup_ip_city,
                   gender,
                   email,
                   total_gamecoin,
                   carrying_gamecoin,
                   safebox_gamecoin,
                   cast(null as bigint) as total_gold_bar,
                   cast(null as bigint) as carrying_gold_bar,
                   cast(null as bigint) as safebox_gold_bar,
                   cast(null as bigint) as carrying_items_value,
                   login_days,
                   login_count,
                   recent_login_series_days,
                   max_login_series_days,
                   last_2nd_login_time,
                   latest_login_time,
                   latest_login_ip_country,
                   latest_login_ip_province,
                   latest_login_ip_city,
                   play_days,
                   ceil(play_duration/60) as play_duration,
                   match_days,
                   ceil(match_duration/60) as match_duration,
                   match_enroll_count,
                   match_innings,
                   pay_sum,
                   pay_count,
                   first_pay_time,
                   last_2nd_pay_time,
                   latest_pay_time,
                   bankrupt_days,
                   bankrupt_count,
                   relieve_days,
                   relieve_count,
                   game_duration_avg30day,
                   game_duration_avg15day,
                   game_duration_avg7day,
                   game_duration_avg3day,
                   t2.trend as game_passion_trend,
                   t2.alteration as game_passion_alteration,
                   payment_amount_avg60day,
                   payment_amount_avg30day,
                   payment_amount_avg15day,
                   payment_amount_avg7day,
                   t3.trend as pay_passion_trend,
                   t3.alteration as pay_passion_alteration
              from veda.texas_user_portrait t1
              left join veda.user_activity_alteration t2
                on (t1.fgamefsk = t2.fgamefsk and t1.fplatformfsk = t2.fplatformfsk and t1.fuid = t2.fuid)
              left join veda.user_payment_alteration t3
                on (t1.fgamefsk = t3.fgamefsk and t1.fplatformfsk = t3.fplatformfsk and t1.fuid = t3.fuid)
            union all
            select t1.fgamefsk,
                   t1.fgamename,
                   t1.fplatformfsk,
                   t1.fplatformname,
                   cast(null as bigint) as fhallfsk,
                   cast(null as string) as fhallname,
                   cast(null as bigint) as fterminaltypefsk,
                   cast(null as string) as fterminaltypename,
                   cast(null as bigint) as fversionfsk,
                   cast(null as string) as fversionname,
                   t1.fuid,
                   signup_time,
                   signup_to_now_days,
                   lifespan,
                   signup_channel_code,
                   signup_device_type,
                   signup_device_pixel,
                   signup_device_imei,
                   signup_ip,
                   country as signup_ip_country,
                   cast(null as string) as signup_ip_province,
                   city as signup_ip_city,
                   gender,
                   email,
                   gamecoins,
                   gamecoins as carrying_gamecoin,
                   cast(0 as bigint) as safebox_gamecoin,
                   cast(null as bigint) as total_gold_bar,
                   cast(null as bigint) as carrying_gold_bar,
                   cast(null as bigint) as safebox_gold_bar,
                   cast(null as bigint) as carrying_items_value,
                   login_days,
                   login_count,
                   recent_login_series_days,
                   max_login_series_days,
                   last_2nd_login_time,
                   latest_login_time,
                   latest_login_ip_country,
                   latest_login_ip_province,
                   latest_login_ip_city,
                   play_days,
                   ceil(play_duration/60) as play_duration,
                   cast(null as int) as match_days,
                   cast(null as int) as match_duration,
                   cast(null as int) as match_enroll_count,
                   cast(null as int) as match_innings,
                   pay_sum,
                   pay_count,
                   first_pay_time,
                   last_2nd_pay_time,
                   latest_pay_time,
                   bankrupt_days,
                   bankrupt_count,
                   relieve_days,
                   relieve_count,
                   game_duration_avg30day,
                   game_duration_avg15day,
                   game_duration_avg7day,
                   game_duration_avg3day,
                   t2.trend as game_passion_trend,
                   t2.alteration as game_passion_alteration,
                   payment_amount_avg60day,
                   payment_amount_avg30day,
                   payment_amount_avg15day,
                   payment_amount_avg7day,
                   t3.trend as pay_passion_trend,
                   t3.alteration as pay_passion_alteration
              from veda.chinese_elephant_chess_user_portrait t1
              left join veda.user_activity_alteration t2
                on (t1.fgamefsk = t2.fgamefsk and t1.fplatformfsk = t2.fplatformfsk and t1.fuid = t2.fuid)
              left join veda.user_payment_alteration t3
                on (t1.fgamefsk = t3.fgamefsk and t1.fplatformfsk = t3.fplatformfsk and t1.fuid = t3.fuid)
        """
        res = self.sql_exe(hql)
        if res != 0:
            return res

        return res


# 实例化执行
a = agg_user_crowd(sys.argv[1:])
a()