spec_table = {
    "blind_rt_fct": "flogged_at",
    "gamecoins_rt_fct": "flogged_at",
    "user_rt_gameparty_fct": "flogged_at",
    "marketing_channel_test_data": "flts_at",
    "pay_center_final_order_fct": "forder_date",
    "pay_center_normal_order_fct": "forder_date",
    "pay_center_repair_cheat_fct": "flts_at",
    "pay_center_unnormal_order_fct": "flts_at"
}

month_part_table = [
    "blind_rt_fct",
    "channel_market_device_type_fct",
    "game_cardtype_cc_fct",
    "gift_finace_fct",
    "marketing_pay_mode_money",
    "pay_game_coin_finace_fct",
    "payment_chan_hour_fct",
    "pay_product_channel_fct",
    "pay_product_fct",
    "user_active_ext_fct",
    "user_active_fct",
    "user_active_first_pay_fct",
    "user_active_version_fct",
    "user_back_fct",
    "user_backflow_party_fct",
    "user_channel_fct",
    "user_device_type",
    "user_feed_fct",
    "user_finance_fct",
    "user_game_age_fct",
    "user_gamecoin_balance",
    "user_gameparty_num_fct",
    "user_generate_order_fct",
    "user_lc_loss_income_fct",
    "user_lc_loss_paycnt_fct",
    "user_loss_fct",
    "user_new_top_pay_fct",
    "user_online_channel_fct",
    "user_payment_hour_fct",
    "user_pay_money_range_fct",
    "user_reg_act_days_fct",
    "user_reg_pay_fct",
    "user_retained_fct",
    "user_retained_login_fct",
    "user_true_active_fct"
]

day_part_table = [
    "by_event_args_fct",
    "by_event_args_new_fct",
    "dc_data_info",
    "gamecoins_rt_fct",
    "gameparty_mustblind_fct",
    "gameparty_mustblind_user_fct",
    "marketing_channel_test_data",
    "pay_center_final_order_fct",
    "pay_center_normal_order_fct",
    "pay_center_repair_cheat_fct",
    "pay_center_unnormal_order_fct",
    "pay_country_channel_fct",
    "pay_country_channel_final_fct",
    "pf_exitroom_fct",
    "pf_gift_sell_fct",
    "pf_goods_buy_fct",
    "pf_goods_list_loading_fct",
    "pf_goods_present_fct",
    "pf_hall_goods_loading_fct",
    "pf_handle_order_fct",
    "pf_order_callback_fct",
    "pf_order_loading_fct",
    "pf_party_loading_fct",
    "pf_player_props_loading_fct",
    "pf_profile_loading_fct",
    "pf_prop_use_fct",
    "pf_room_goods_loading_fct",
    "pf_safebox_enter_loading_fct",
    "pf_safebox_loading_fct",
    "pf_safebox_operate_fct",
    "pf_safebox_pwd_fct",
    "pf_shop_loading_fct",
    "pf_startplay_fct",
    "pf_user_sit_down_fct",
    "real_time_stream",
    "user_channel_promo_online_fct",
    "user_coin_stream_fct",
    "user_flow_loss_fct",
    "user_goods_stream_fct",
    "user_point_stream_fct",
    "user_rt_gameparty_fct"
]
